#!/bin/bash

NODE_VERSION="6.5"
SCRIPT_DIR=$(cd $(dirname $0);pwd)
cd $SCRIPT_DIR

function usage {
    cat << _BUFF_
Usage: gengar [options]
  -i install
  -s run screenshot
  -c run compare
_BUFF_
}

while getopts :isc OPTS
do
    case ${OPTS} in
        i)
            echo -n 'BrowserStack Username ?> '
            read BROWSER_STACK_USERNAME
            echo -n 'BrowserStack Access Key ?> '
            read BROWSER_STACK_ACCESS_KEY
            BUFF=`cat UItest/bin/config/.setting.js | sed s/{BROWSER_STACK_USERNAME}/$BROWSER_STACK_USERNAME/g | sed s/{BROWSER_STACK_ACCESS_KEY}/$BROWSER_STACK_ACCESS_KEY/g`
            echo "$BUFF" > UItest/bin/config/setting.js
            docker run -t --rm -v $SCRIPT_DIR/UItest:/usr/src/UItest -w /usr/src/UItest node:$NODE_VERSION npm install
            exit 0
            ;;

        s)
            docker run -t --rm -v $SCRIPT_DIR/UItest:/usr/src/UItest -w /usr/src/UItest node:$NODE_VERSION npm run screenshot
            exit 0
            ;;

        c)
            docker run -t --rm -v $SCRIPT_DIR/UItest:/usr/src/UItest -w /usr/src/UItest node:$NODE_VERSION npm run compare
            exit 0
            ;;

        *)
            usage
            exit 1
            ;;
  esac
done

usage
exit 1
